#!/usr/bin/env bash
# performing a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_replacement="server_name _;\n\trewrite ^\/redirect_me http:\/\/github.com\/emmanuelofor permanent;"

sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
