#!/usr/bin/env bash
# Script that creates the file /var/run/myscript.pid containing its PID
# and displays 'To infinity and beyond indefinitely'
# and displays 'I hate the kill' command when receiving a SIGTERM signal
# and displays 'Y U no love me?!' when receiving a SIGINT signal
# The script also deletes the file /var/run/myscript.pid and terminates itself while receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do 
    echo 'To infinity and beyond' 
    sleep 2
done
