#!/usr/bin/env bash
# Script that displays 'To infinity and beyond' indefinitely
# Requirement: Add a sleep 2 in between each iteration of the loop

while true
do
    echo "To infinity and beyond"
    sleep 2
done
