#!/usr/bin/env bash
#A script that parses Apache log files in list format
#  It groups visitors by IP and HTTP status code
#  It displays the number of occurrences, IP, and HTTP status
#  and code of each log, in sorted order.

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
