#!/usr/bin/env bash
# This is a  script which  displays the content of the current directory in list format
# The script only displays the part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
